name: Publish to Winget

on:
  release:
    types: [released]

permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: o9-9.DiscordBotClient
          token: ${{ secrets.WINGET_TOKEN }}
